import { Car, Sofa, Tv, Lamp, Drill, Shirt, Building, Landmark, ClipboardList } from 'lucide-react-native';

export const CATEGORIES = [
  { name: 'Furniture', icon: Sofa, color: '#FFC107' },
  { name: 'Electronics', icon: Tv, color: '#17A2B8' },
  { name: 'Vehicles', icon: Car, color: '#DC3545' },
  { name: 'Home Decor', icon: Lamp, color: '#28A745' },
  { name: 'Tools', icon: Drill, color: '#007BFF' },
  { name: 'Apparel', icon: Shirt, color: '#6C757D' },
  { name: 'Property for Rent', icon: Building, color: '#FF5722' },
  { name: 'Property for Sale', icon: Landmark, color: '#4CAF50' },
  { name: 'Off-Plan Properties', icon: ClipboardList, color: '#9C27B0' },
];

export const LISTINGS = [
  {
    id: '1',
    title: 'Modern Leather Sofa',
    price: '1200 AED',
    category: 'Furniture',
    image: 'https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'Slightly used modern leather sofa, great condition. No pets, no smoking household.',
    seller: 'Ahmed M.',
    location: 'Dubai Marina',
  },
  {
    id: '2',
    title: 'Samsung 55" 4K Smart TV',
    price: '1500 AED',
    category: 'Electronics',
    image: 'https://images.pexels.com/photos/5721865/pexels-photo-5721865.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: '2 years old, perfect working condition with remote and original box.',
    seller: 'Fatima K.',
    location: 'Downtown Dubai',
  },
  {
    id: '3',
    title: 'Toyota Camry 2018',
    price: '45000 AED',
    category: 'Vehicles',
    image: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'GCC specs, full service history, no accidents. Low mileage.',
    seller: 'Yusuf A.',
    location: 'Sharjah',
  },
  {
    id: '4',
    title: 'Antique Brass Table Lamp',
    price: '250 AED',
    category: 'Home Decor',
    image: 'https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'Beautiful vintage lamp, adds character to any room. Bulb included.',
    seller: 'Sara B.',
    location: 'Jumeirah',
  },
  {
    id: '5',
    title: 'Bosch Power Drill Set',
    price: '350 AED',
    category: 'Tools',
    image: 'https://images.pexels.com/photos/1249613/pexels-photo-1249613.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'Complete set with multiple bits and carrying case. Barely used.',
    seller: 'Omar S.',
    location: 'Al Barsha',
  },
  {
    id: '6',
    title: 'Designer Men\'s Shirt',
    price: '150 AED',
    category: 'Apparel',
    image: 'https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'Brand new, never worn. Size Medium.',
    seller: 'Layla R.',
    location: 'Deira',
  },
  {
    id: '7',
    title: 'Luxury Villa for Sale',
    price: '3,500,000 AED',
    category: 'Property for Sale',
    propertyType: 'for_sale', // New field
    image: 'https://images.pexels.com/photos/164005/pexels-photo-164005.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'Spacious 5-bedroom villa with private pool and garden.',
    seller: 'Property Group',
    location: 'Palm Jumeirah',
  },
  {
    id: '8',
    title: 'Studio Apartment for Rent',
    price: '4,000 AED/month',
    category: 'Property for Rent',
    propertyType: 'for_rent', // New field
    image: 'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'Fully furnished studio in a prime location, all bills included.',
    seller: 'Rentals Inc.',
    location: 'Business Bay',
  },
  {
    id: '9',
    title: 'Commercial Land Plot',
    price: '1,800,000 AED',
    category: 'Off-Plan Properties',
    propertyType: 'for_sale', // New field
    image: 'https://images.pexels.com/photos/269077/pexels-photo-269077.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'Ideal for commercial development, close to major highways.',
    seller: 'Land Developers',
    location: 'Jebel Ali',
  },
  {
    id: '10',
    title: '2-Bedroom Apartment for Sale',
    price: '1,100,000 AED',
    category: 'Property for Sale',
    propertyType: 'for_sale',
    image: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'Modern apartment with city views, excellent amenities.',
    seller: 'Urban Living',
    location: 'Downtown Dubai',
  },
  {
    id: '11',
    title: 'Townhouse for Rent',
    price: '8,500 AED/month',
    category: 'Property for Rent',
    propertyType: 'for_rent',
    image: 'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'Family-friendly townhouse with garden access.',
    seller: 'Community Homes',
    location: 'Arabian Ranches',
  },
];

export const EMIRATES = [
  'Abu Dhabi',
  'Ajman',
  'Al Ain',
  'Dubai',
  'Fujairah',
  'Ras Al Khaimah',
  'Sharjah',
  'Umm Al Quwain',
];
